language: cpp
sudo: required
dist: trusty

os:
 - linux

env:
  global:
    - QTDIR=/opt/qt55

install:
 - ./install.sh

before_script:
 - qmake --version
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3

script:
 - ./compile.sh
 - ./build/openPSTD test