language: cpp
sudo: required
dist: trusty

env:
  global:
    - secure: I3mWRLOhfZVSV2OeGM/5ZOaCDmxiYGRvsOJC+43TDeRSaoUulapR+J9N86L/Qig7aTQhtJ+r9x5VTZV1JaMkeVTZ+5vtbvQ3oosFcTrVXAuTxvzmVQVznhOyIreDHEyh+WNg9Wdh1igjY397lvxmZOIXNBeyBcZL5Zz3PffwnRUuU4pUML1BoCrt5NaN4Q2MT+bcOtER+qMo3duk0zpZHX02D7hac7pTBW4IVvikhUKHZw+Hpui+H/a+/HkeIyFjFABmWDyBI5ackmqRTiznZHc8j3Y8IGTUPC62M+2FcxpbbWF/pLnLW3RvCpAqWwMDLAIioBnBKhomOdWVLUhHtTYn6O4JUFEhcBZ7vUzWvrbBHMqj1XGSoLQ/ufxt3tGvRxMSbZUm3buySJhUHkE+MVY6EKPG7ZpFW913Asg7CW5LzKwdtR4bLZfNswQ9xX1elhETblGIw2ph/mu0HIWSh4q6+rrEsnD6KzirjzX6gtgxp47d53Nc0PeJ5+jIMVVWfwclWy2LgpWolIOGCPoOnKxt5hhyu/p2IfpwMh6JSwLESSsqh7EFD68B8c8zCQGZhKGrEqlQTKaRqB/DV0+bMAYeKmDc+ga/Kg8fE4Skt0r/ibRdk3sVovPwrpZ4zHzB66oyIS17AJRYcfNBI5Rh77e7WXlaonBzIJGWfHConwI=
    - GH_REF=github.com/openPSTD/openPSTD.git


before_install:
- sudo chmod 777 -R build
- export PATH=./build/:$PATH
- export PATH=/opt/qt55/bin/:$PATH
- sudo add-apt-repository --yes ppa:beineri/opt-qt55-trusty
- sudo apt-get update -qq

install:
- install_unqlite.sh
- install_Qt55.sh
- install_boost.sh
- install_rapidjson.sh
- install_eigen.sh

before_script:
- uname -r
- gcc -v
- cmake --version

script:
- compile.sh
- test.sh

deploy:
- publish.sh