language: cpp

sudo: required

dist: trusty

before_install:
 - sudo chmod 777 -R build
 - export PATH=./build/:$PATH
# - export PATH=/opt/qt55/bin/:$PATH
 - uname -r
 - gcc -v
 - cmake --version
 - sudo apt-get update -qq

install:
# - install_cmake33.sh
 - install_unqlite.sh
 - install_Qt55.sh
 - install_boost.sh
 - install_rapidjson.sh

before_script:
# - execute_uic.sh
 - uname -r
 - gcc -v
 - cmake --version

script: 
 - compile.sh
