language: cpp

sudo: required

dist: trusty

before_install:
 - sudo chmod 777 -R build
 - export PATH=./build/:$PATH
 - sudo apt-get update -qq

install:
 - install_unqlite.sh
 - install_Qt55.sh
 - rcc Resources.qrc
 - install_boost.sh
 - install_rapidjson.sh

before_script:
 - uname -r
 - gcc -v
 - cmake --version

script: 
 - compile.sh
