language: cpp

sudo: required

dist: trusty

before_install:
 - sudo chmod 777 -R build
 - export PATH=./build/:$PATH
 - export PATH=/opt/qt55/bin/:$PATH
 - deb http://ppa.launchpad.net/beineri/opt-qt55-trusty/ubuntu trusty main
 - deb-src http://ppa.launchpad.net/beineri/opt-qt55-trusty/ubuntu trusty main 
# - sudo add-apt-repository --yes ppa:beineri/opt-qt55
 - sudo apt-get update -qq

install:
 - install_unqlite.sh
 - install_Qt55.sh
 - rcc Resources.qrc
 - install_boost.sh
 - install_rapidjson.sh

before_script:
 - uname -r
 - gcc -v
 - cmake --version

script: 
 - compile.sh
