language: cpp
sudo: required
dist: trusty

os:
- linux
- osx

env:
  global:
  - OPENPSTD_MAJOR_VERSION=2
  - OPENPSTD_MINOR_VERSION=0

before_install:
- sudo chmod -R +x build
- export PATH=./build/:$PATH
- export PATH=/opt/qt55/bin/:$PATH
- install_add_repo.sh

install:
- install_boost.sh
- install_xsltproc.sh
- install_unqlite.sh
- install_Qt55.sh
- install_rapidjson.sh
- install_eigen.sh

before_script:
- uname -r
- gcc -v
- cmake --version
- cmake --help
- cpack --version
- cpack --help

script:
- compile.sh
- test.sh

after_success:
- upload_webdav.sh