language: cpp

sudo: required

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - apt-cache search qt
 - wget http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2/download
 - tar -xvzf boost_1_54_0.tar.gz
 - cd boost_1_54_0/
 - ./bootstrap.sh --with-libraries=program_options
 - cd ../

install:
 - cd boost_1_54_0/
 - sudo ./b2 install
 - cd ../
 - sudo apt-get install libqt5widgets5 libqt5opengl5 libqt5core5

script: 
 - cmake -G Unix\ Makefiles
 - make