language: cpp
sudo: required
dist: trusty

notifications:
  email: false

os:
 - linux

env:
  global:
    - QTDIR=/opt/qt55

install:
 - ./install.sh

before_script:
 - qmake --version
 - ./opendisplay.sh

script:
 - ./compile.sh
 - ./build/openPSTD test